version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: eof_user
      POSTGRES_PASSWORD: eof_password
      POSTGRES_DB: eof_scraper
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eof_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build: .
    command: python scheduler.py
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_URL: postgresql://eof_user:eof_password@postgres:5432/eof_scraper
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  api:
    build: .
    command: python api_enhanced.py
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_URL: postgresql://eof_user:eof_password@postgres:5432/eof_scraper
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
