name: Deploy to Hetzner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Navigate to app directory
          cd /var/www/drugalert || cd /opt/drugalert.gr || exit 1
          
          # Pull latest changes
          git fetch origin
          git reset --hard origin/main
          
          # Update Python dependencies
          source venv/bin/activate
          pip install -r requirements.txt
          
          # Build frontend
          cd frontend
          npm install
          npm run build
          cd ..
          
          # Set permissions
          chown -R www-data:www-data .
          
          # Restart services
          systemctl restart drugalert-api || systemctl restart drugalert-backend || true
          systemctl restart drugalert-scheduler || true
          
          # Restart PM2
          pm2 restart drugalert-frontend || pm2 restart all || true
          pm2 save
          
          # Reload nginx
          nginx -t && systemctl reload nginx
          
          echo "Deployment completed successfully!"
