name: Deploy to Hetzner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 188.245.198.35
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /root/eof-scraper
          git pull origin main
          
          # Backend setup
          cd backend
          source venv/bin/activate
          pip install -r requirements.txt
          pkill -f "uvicorn api:app" || true
          nohup python -m uvicorn api:app --host 0.0.0.0 --port 8443 > /var/log/drugalert-backend.log 2>&1 &
          
          # Frontend setup
          cd ../frontend
          npm install
          npm run build
          pm2 restart drugalert-frontend || pm2 start npm --name "drugalert-frontend" -- start
          
          # Restart nginx
          systemctl restart nginx
